input_path: /Volumes/Seagate/Chris/2012_Images
input_year: 2012
a_or_b: "A"

# start_year: 2017
# start_month: 7
# start_day: 20

# end_year: 2017
# end_month: 8
# end_day: 15

start_time: "09:35:00"
end_time: "18:35:25"

specific_dates: 
  - "2017-08-20"
  - "2017-08-25"
  - "2017-08-29"
  - "2017-09-03"
  - "2017-09-06"
  - "2017-09-11"