# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 2010_images, dev ]
  pull_request:
    branches: [ 2010_images, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-code:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3




      # Runs a set of commands using the runners shell
      - name: Process Images
        env:
          ACTIONS_RUNNER_HOOK_JOB_STARTED: /Users/crura/Documents/bin/ssw
        run: |
          source /Users/crura/miniconda3/etc/profile.d/conda.sh &&
          conda init bash &&
          conda activate test_env &&
          python3 -m venv env &&
          source env/bin/activate &&
          pip install -r requirements.txt &&
          git_repo=$(git rev-parse --show-toplevel) &&
          # export SSW /Users/crura/SSW
          # source $SSW/gen/setup/setup.ssw \loud
          export IDL_DIR="/Applications/harris/idl89" &&
          export secchi="/Volumes/Seagate/Chris/sswdb/secchi" &&
          export SECCHI_BKG="/Users/crura/stereo/secchi/backgrounds" &&
          export SSWDB="/Volumes/Seagate/Chris/sswdb" &&
          export sdb="/Volumes/Seagate/Chris/sswdb" &&
          export VSO_SERVER="http://netdrms02.nispdc.nso.edu/cgi/vsoi_tabdelim" &&

          (echo "ssw_path" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/string/strjustify.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/system/strrep_logenv.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/string/prstr.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/genutil/uniqo.pro'" &&
          echo "ssw_path, '/Users/crura/SSW/gen'" &&
          echo "ssw_path, '/Users/crura/SSW/hinode'" &&
          echo "ssw_path, '/Users/crura/SSW/offline'" &&
          echo "ssw_path, '/Users/crura/SSW/proba2'" &&
          echo "ssw_path, '/Users/crura/SSW/sdo'" &&
          echo "ssw_path, '/Users/crura/SSW/site'" &&
          echo "ssw_path, '/Users/crura/SSW/so'" &&
          echo "ssw_path, '/Users/crura/SSW/soho'" &&
          echo "ssw_path, '/Users/crura/SSW/stereo'" &&
          echo "ssw_path, '/Users/crura/SSW/trace'" &&
          echo "ssw_path, '//Users/crura/SSW/vobs'" &&
          echo "ssw_path, '/Users/crura/SSW/packages'" &&
          echo ".compile -v '/Users/crura/Desktop/Research/idlroutines/download.pro'" &&
          echo ".compile -v '/Users/crura/SSW/packages/forward/idl/DEFAULTS/for_settingdefaults.pro'" &&
          echo ".compile -v '/Users/crura/SSW/gen/idl/util/default.pro'" &&
          echo ".compile -v '/Users/crura/IDLWorkspace/Default/linspace.pro'" &&
          echo ".compile -v '$git_repo/stereo_process_new.pro'" &&
          echo "stereo_process_new('/Volumes/Seagate/Chris/2010_Images_match/B/test')" &&
          cat) |
          /Users/crura/Documents/bin/ssw
          deactivate

